JAZZMIN_SETTINGS = {
    "site_title": "SKUD",
    "site_header": "SKUD",
    "site_brand": "SKUD",
    "site_logo_classes": "img-circle",
    "site_icon": "",
    "welcome_sign": "Welcome to the SKUD admin",
    "copyright": "SAMYY SOFT Ltd",
    "user_avatar": None,
    "show_sidebar": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth.user": "fas fa-user-circle",
        "auth.group": "fas fa-shield-alt",
        "devices.Device": "fas fa-camera",
        "orders.order": "fas fa-receipt",
        "users.user": "fas fa-user",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": 'custom_admin/main.css',
    "use_google_fonts_cdn": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_fixed": True,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar_nav_legacy_style": True,
}
