JAZZMIN_SETTINGS = {
    "site_title": "SKUD",
    "site_header": "SKUD",
    "site_brand": "SKUD",
    "site_logo_classes": "img-circle",
    "site_icon": "",
    "welcome_sign": "Welcome to the SKUD admin",
    "copyright": "SAMYY SOFT Ltd",
    "user_avatar": None,
    "show_sidebar": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth",
        "employees",
        "devices",

        "auth.user",
        "auth.group",
        "devices.device",
        "employees.employee",
        "devices.event",
        "authtoken",
    ],
    "icons": {
        "auth.user": "fas fa-user-circle",
        "auth.group": "fas fa-shield-alt",
        "devices.device": "fas fa-camera",
        "orders.order": "fas fa-receipt",
        "employees.employee": "fas fa-user-tie",
        "devices.event": "fas fa-address-book",
        "devices.webhook": "fas fa-globe",
        "authtoken.tokenproxy": "fas fa-lock",
    },
    "default_icon_parents": "fas fa-circle",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": 'custom_admin/main.css',
    "use_google_fonts_cdn": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_fixed": True,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_disable_expand": True,
}
