# Generated by Django 5.1.3 on 2024-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Company', 'Company'), ('Admin', 'Admin. Dept.'), ('Sales', 'Sales Dept.'), ('Financial', 'Financial Dept.'), ('Production', 'Production Dept.')], max_length=100)),
                ('floor_num', models.IntegerField()),
                ('room_num', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=7)),
                ('user_type', models.CharField(choices=[('normal', 'Normal User'), ('visitor', 'Visitor'), ('blackList', 'Blocklist User')], max_length=9)),
                ('lifetime_user', models.BooleanField()),
                ('begin_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('local_ui_right', models.BooleanField()),
                ('face_image', models.ImageField(blank=True, help_text='No larger than 200 KB. JPG, JPEG, PNG allowed.', max_length=200, null=True, upload_to='faces/')),
                ('pin', models.CharField(help_text='Enter a secure PIN.', max_length=10)),
                ('authentication_type', models.CharField(choices=[('same_as_device', 'Same as Device'), ('custom', 'Custom')], default='same_as_device', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='foods')),
            ],
        ),
    ]
