# Generated by Django 5.1.3 on 2024-11-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_employee_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_size', models.CharField(choices=[('0.5', 'Kichik'), ('1.0', "O'rta"), ('1.5', 'Katta')], max_length=3)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
