# Generated by Django 5.1.3 on 2024-11-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_order_delete_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='authentication_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='floor_num',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lifetime_user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='local_ui_right',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='room_num',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_type',
        ),
    ]
